"""Add temporary pin

Revision ID: 2ff7e9085a54
Revises: 71762e3462cd
Create Date: 2018-03-25 18:49:23.347850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ff7e9085a54'
down_revision = '71762e3462cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('temp_pin', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'temp_pin')
    # ### end Alembic commands ###
