"""Add backlogged boolean (unused)

Revision ID: 71762e3462cd
Revises: 7353599ce530
Create Date: 2017-10-11 19:14:24.506794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71762e3462cd'
down_revision = '7353599ce530'
branch_labels = None
depends_on = None


def upgrade():
    print('Nothing')
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade():
    print('Nothing')
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
