"""Rename project to project_id to not conflict with relationship on Projects table

Revision ID: 7353599ce530
Revises: 0e111e24ee0f
Create Date: 2017-09-30 21:29:01.956880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7353599ce530'
down_revision = '0e111e24ee0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('project_id', sa.Integer(), nullable=True))
    op.drop_constraint('tasks_project_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'])
    op.drop_column('tasks', 'project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('project', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_project_fkey', 'tasks', 'projects', ['project'], ['id'])
    op.drop_column('tasks', 'project_id')
    # ### end Alembic commands ###
